name: "kafka"
services:
  kafka:
    image: 'apache/kafka:4.1.1'
    container_name: kafka
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_NODE_ID=0
      # 节点角色
      - KAFKA_PROCESS_ROLES=controller,broker
      # 控制器集群的投票节点列表
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # 定义容器中暴露的端口，在同一网络的docker容器暴露9092端口，外部访问暴露9094端口
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      # 告诉客户端的访问地址
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - '9092:9092'
      - '9094:9094'
      - '9093:9093'
    volumes:
      - kafka_data:/var/lib/kafka/data
volumes:
  kafka_data:
    driver: local